name: Post-install/importing issue
description: Report an issue if you have trouble importing `simpeg` after installation.
title: "<Please write a comprehensive title here>"
labels: [Installation]

body:
- type: textarea
  attributes:
    label: "Steps to reproduce:"
    description: >
      Please describe the installation method (e.g. building from source,
      Anaconda, pip), your OS and SimPEG, NumPy, Scipy, and Python version information.
    placeholder: |
      If running in a conda environment you could paste the output of `conda list` here.
  validations:
    required: true

- type: textarea
  attributes:
    label: "Error message:"
    description: >
      Please include full error message, if any.
    placeholder: |
      << Full traceback starting from `Traceback: ...` >>
    render: shell

- type: textarea
  attributes:
    label: "Additional information:"
    description: Please add any additional information that could help us diagnose the problem better.
