jobs:
  # Build docs only on scheduled jobs or on a relase
  - job: BuildDocs
    condition: or(eq(variables['Build.Reason'], 'Schedule'), startsWith(variables['build.sourceBranch'], 'refs/tags/'))
    pool:
      vmImage: ubuntu-latest
    variables:
      python.version: "3.8"
    timeoutInMinutes: 240
    steps:
      # Checkout simpeg repo.
      # Sync tags and disable shallow depth to get the SimPEG version.
      - checkout: self
        fetchDepth: 0
        fetchTags: true
        displayName: Checkout repository (including tags)

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: .ci/azure/setup_env.sh
        displayName: Setup SimPEG environment

      - bash: |
          source activate simpeg-test
          make -C docs html
        displayName: Building documentation

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(Build.SourcesDirectory)/docs/_build/html
          artifactName: built-docs
        displayName: "Upload docs as artifact"

  - job: DeployRelease
    dependsOn: BuildDocs
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 240
    steps:
      # Checkout simpeg repo.
      # Sync tags and disable shallow depth to get the SimPEG version.
      - checkout: self
        fetchDepth: 0
        fetchTags: true
        displayName: Checkout repository (including tags)

      - bash: |
          git config --global user.name ${GH_NAME}
          git config --global user.email ${GH_EMAIL}
          git config --list | grep user.
        displayName: "Configure git"
        env:
          GH_NAME: $(gh.name)
          GH_EMAIL: $(gh.email)

      - bash: |
          mkdir -p docs/_build/html
        displayName: "Create directory for built docs"

      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: built-docs
          targetPath: docs/_build/html
        displayName: "Download docs artifact"

      # Upload release build of the docs to gh-pages branch in simpeg/simpeg-docs
      - bash: .ci/azure/deploy-release-docs.sh
        displayName: Push documentation to simpeg-docs
        env:
          GH_TOKEN: $(gh.token)

  - job: DeployDev
    dependsOn: BuildDocs
    condition: eq(variables['Build.Reason'], 'Schedule') # run only scheduled triggers
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 240
    steps:
      # Checkout simpeg repo.
      # Sync tags and disable shallow depth to get the SimPEG version.
      - checkout: self
        fetchDepth: 0
        fetchTags: true
        displayName: Checkout repository (including tags)

      - bash: |
          git config --global user.name ${GH_NAME}
          git config --global user.email ${GH_EMAIL}
          git config --list | grep user.
        displayName: "Configure git"
        env:
          GH_NAME: $(gh.name)
          GH_EMAIL: $(gh.email)

      - bash: |
          mkdir -p docs/_build/html
        displayName: "Create directory for built docs"

      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: built-docs
          targetPath: docs/_build/html
        displayName: "Download docs artifact"

      # Upload dev build of the docs to a dev branch in simpeg/simpeg-docs
      # and update submodule in the gh-pages branch
      - bash: .ci/azure/deploy-dev-docs.sh
        displayName: Push documentation to simpeg-docs (dev branch)
        env:
          GH_TOKEN: $(gh.token)
