jobs:
  - job:
    displayName: Deploy Docs
    pool:
      vmImage: ubuntu-latest
    variables:
      python.version: "3.8"
    timeoutInMinutes: 240
    steps:
      # Checkout simpeg repo, including tags.
      # We need to sync tags and disable shallow depth in order to get the
      # SimPEG version while building the docs.
      - checkout: self
        fetchDepth: 0
        fetchTags: true
        displayName: Checkout repository (including tags)

      - script: |
          git config --global user.name ${GH_NAME}
          git config --global user.email ${GH_EMAIL}
          git config --list | grep user.
        displayName: "Configure git"
        env:
          GH_NAME: $(gh.name)
          GH_EMAIL: $(gh.email)

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: .ci/azure/setup_env.sh
        displayName: Setup SimPEG environment

      - script: |
          source activate simpeg-test
          python -m build --no-isolation --skip-dependency-check --sdist .
          twine upload --skip-existing dist/*
        displayName: Deploy source
        env:
          TWINE_USERNAME: $(twine.username)
          TWINE_PASSWORD: $(twine.password)

      - script: |
          source activate simpeg-test
          cd docs
          make html
          cd ..
        displayName: Building documentation

      # upload documentation to simpeg-docs gh-pages on tags
      - script: |
          git clone --depth 1 https://${GH_TOKEN}@github.com/simpeg/simpeg-docs.git
          cd simpeg-docs
          git gc --prune=now
          git remote prune origin
          rm -rf *
          cp -r $BUILD_SOURCESDIRECTORY/docs/_build/html/* .
          cp $BUILD_SOURCESDIRECTORY/docs/README.md .
          touch .nojekyll
          echo "docs.simpeg.xyz" >> CNAME
          git add .
          git commit -am "Azure CI commit ref $(Build.SourceVersion)"
          git push
        displayName: Push documentation to simpeg-docs
        env:
          GH_TOKEN: $(gh.token)
