jobs:
  - job: First
    steps:
      # Don't checkut simpeg repo
      - checkout: none

      # Set variable for future use
      - bash: |
          git_version=$(git --version)
          echo "$git_version"
          echo "##vso[task.setvariable variable=git_version;isoutput=true]$git_version"
        name: git_version

  - job: Second
    dependsOn: First
    variables:
      git_version: $[ dependencies.First.outputs['git_version.git_version'] ]
      docsRepo: github.com/simpeg/simpeg-doctest.git
    steps:
      # Don't checkut simpeg repo
      - checkout: none

      - bash: |
          git_version=$(git_version)
          echo "Git version: $(git_version)"
          echo "Git version: ${git_version}"

      - bash: |
          echo "Repo: $(docsRepo)"
