jobs:
  - job: First
    steps:
      # Set variable for future use
      - bash: |
          pythonVersion=$(python --version)
          echo "##vso[task.setvariable variable=pythonVersion;isoutput=true]Python version"
        name: pythonVersion

  - job: Second
    dependsOn: First
    variables:
      - pythonVersion: $[ dependencies.First.outputs['passOutput.pythonVersion'] ]
      - docsRepo: github.com/simpeg/simpeg-doctest.git
    steps:
      - bash: |
          echo "Python version: $pythonVersion"

      - bash: |
          git clone -q --branch gh-pages --depth 1 https://${GH_TOKEN}@$(docs_repo)
