jobs:
  - job: First
    steps:
      # Set variable for future use
      - bash: |
          git_version=$(git --version)
          echo "##vso[task.setvariable variable=git_version;isoutput=true]$git_version"
        name: pythonVersion

  - job: Second
    dependsOn: First
    variables:
      git_version: $[ dependencies.First.outputs['passOutput.git_version'] ]
      docsRepo: github.com/simpeg/simpeg-doctest.git
    steps:
      - bash: |
          echo "Git version: $git_version"

      - bash: |
          git clone -q --branch gh-pages --depth 1 https://${GH_TOKEN}@$(docsRepo)
