jobs:
  - job: First
    steps:
      # Set variable for future use
      - bash: |
          python_version=$(python --version)
          echo "##vso[task.setvariable variable=python_version;isoutput=true]Python version"
        name: python_version

  - job: Second
    dependsOn: First
    variables:
      - python_version: $[ dependencies.First.outputs['passOutput.python_version'] ]
      - docs_repo: github.com/simpeg/simpeg-doctest.git
    steps:
      - bash: |
          echo "Python version: $python_version"

      - bash: |
          git clone -q --branch gh-pages --depth 1 https://${GH_TOKEN}@$(docs_repo)
