parameters:
  os : ['ubuntu-latest']
  py_vers: ['3.8']
  test: ['tests/em',
         'tests/base tests/flow tests/seis tests/utils tests/meta',
         'tests/docs -s -v',
         'tests/examples/test_examples_1.py',
         'tests/examples/test_examples_2.py',
         'tests/examples/test_examples_3.py',
         'tests/examples/test_tutorials_1.py tests/examples/test_tutorials_2.py',
         'tests/examples/test_tutorials_3.py',
         'tests/pf',
         'tests/dask', # This must be ran on it's own to avoid modifying the code from any other tests.
         ]

jobs:
  - ${{ each os in parameters.os }}:
    - ${{ each py_vers in parameters.py_vers }}:

      # -----------------------------------------------------------------------
      # Create conda environment and cache it for future use
      - job: SetupEnv${{ py_vers}}${{ os }}
          displayName: Setup conda environment
          pool:
            vmImage: ${{ os }}
          steps:
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add conda to PATH

          - bash: .ci/azure/setup_env.sh
            displayName: Setup SimPEG environment

          - bash: |
              sudo chown -R $(whoami):$(id -ng) $(CONDA_CACHE_DIR)
            displayName: Fix CONDA_CACHE_DIR directory permissions

          - task: Cache@2
            displayName: Use cached Anaconda environment
            inputs:
              key: 'conda | "${{ os }}" | "${{ py_vers }}"'
              path: $(CONDA_CACHE_DIR)
              cacheHitVar: CONDA_CACHE_RESTORED
      # -----------------------------------------------------------------------

      - ${{ each test in parameters.test }}:
        - job:
          displayName: ${{ os }}_${{ py_vers }}_${{ test }}
          pool:
            vmImage: ${{ os }}
          timeoutInMinutes: 120
          variables:
            python.version: ${{ py_vers }}
            test.target: ${{ test }}
          steps:

          # Checkout simpeg repo, including tags.
          # We need to sync tags and disable shallow depth in order to get the
          # SimPEG version while building the docs.
          - checkout: self
            fetchDepth: 0
            fetchTags: true
            displayName: Checkout repository (including tags)

          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add conda to PATH

          - bash: .ci/azure/setup_env.sh
            displayName: Setup SimPEG environment
            condition: eq(variables.CONDA_CACHE_RESTORED, 'false')

          - bash: .ci/azure/run_tests_with_coverage.sh
            displayName: 'Testing ${{ test }}'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(Build.SourcesDirectory)/docs/_build/html
              artifactName: html_docs
            displayName: 'Publish documentation artifact'
            condition: eq('${{ test }}', 'tests/docs -s -v')

          - script: |
              curl -Os https://uploader.codecov.io/latest/linux/codecov
              chmod +x codecov
              ./codecov
            displayName: 'Upload coverage to codecov.io'
