parameters:
  os : ['ubuntu-latest']
  py_vers: ['3.11']
  test: ['tests/em',
         'tests/base tests/flow tests/seis tests/utils',
         'tests/meta',
         'tests/docs -s -v',
         'tests/examples/test_examples_1.py',
         'tests/examples/test_examples_2.py',
         'tests/examples/test_examples_3.py',
         'tests/examples/test_tutorials_1.py tests/examples/test_tutorials_2.py',
         'tests/examples/test_tutorials_3.py',
         'tests/pf',
         'tests/dask', # This code must be tested on its own to avoid modifying the implementation for any other tests.
         ]

jobs:
  - ${{ each os in parameters.os }}:
    - ${{ each py_vers in parameters.py_vers }}:

      # -----------------------------------------------------------------------
      # Create conda environment
      - job: ${{ replace(os, '-', '_') }}_${{ replace(py_vers, '.', '') }}
        displayName: "Cache conda environment"
        pool:
          vmImage: ${{ os }}
        variables:
          python.version: ${{ py_vers }}
        steps:
          - bash: echo "Trying new job here"

          # Checkout simpeg repo to get the environment file.
          - checkout: self

          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add conda to PATH

          - bash: .ci/azure/setup_env.sh
            displayName: "Setup SimPEG environment"

          - bash: |
              echo "echo $CONDA"
              echo $CONDA
              echo "ls $CONDA"
              ls $CONDA
              echo "ls $CONDA/envs"
              ls $CONDA/envs

          - bash : |
              envname=$(grep -e "^name:" .ci/environment_test.yml | cut -f 2 -d ":" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
              echo $envname
              echo "##vso[task.setvariable variable=envname]$envname"
            displayName: "Get name of environment"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(CONDA)/envs/$(envname)
              artifactName: environment-${{ os }}-${{ py_vers }}
            displayName: "Upload conda environment as artifact"

      # -----------------------------------------------------------------------

      - ${{ each test in parameters.test }}:
        - job:
          displayName: ${{ os }}_${{ py_vers }}_${{ test }}
          dependsOn: ${{ replace(os, '-', '_') }}_${{ replace(py_vers, '.', '') }}
          pool:
            vmImage: ${{ os }}
          timeoutInMinutes: 120
          variables:
            python.version: ${{ py_vers }}
            test.target: ${{ test }}
          steps:

          # Checkout simpeg repo, including tags.
          # We need to sync tags and disable shallow depth in order to get the
          # SimPEG version while building the docs.
          - checkout: self
            fetchDepth: 0
            fetchTags: true
            displayName: Checkout repository (including tags)

          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add conda to PATH

          - bash: |
              echo "$(envname)"
              mkdir "$CONDA"/envs/simpeg-test
            displayName: "Create directory for environment"

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: environment-${{ os }}-${{ py_vers }}
              path: $(CONDA)/envs/simpeg-test/
            displayName: "Download conda environment artifact"

          - bash: |
              sudo chown -R $(whoami):$(id -ng) "$CONDA/envs"
              sudo chmod +x "$CONDA"/envs/simpeg-test/bin/*
            displayName: Fix conda directory permissions

          - bash: |
              set -x
              ls -la $CONDA/envs
              ls -la $CONDA/envs/simpeg-test
              ls -la $CONDA/envs/simpeg-test/bin

          - bash: .ci/azure/run_tests_with_coverage.sh
            displayName: 'Testing ${{ test }}'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(Build.SourcesDirectory)/docs/_build/html
              artifactName: html_docs
            displayName: 'Publish documentation artifact'
            condition: and(eq('${{ test }}', 'tests/docs -s -v'), succeededOrFailed())

          - bash: |
              job="${{ os }}_${{ py_vers }}_${{ test }}"
              jobhash=$(echo $job | sha256sum | cut -f 1 -d " " | cut -c 1-7)
              cp coverage.xml "coverage-$jobhash.xml"
              echo "##vso[task.setvariable variable=jobhash]$jobhash"
            condition: succeededOrFailed()
            displayName: 'Rename coverage report'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(Build.SourcesDirectory)/coverage-$(jobhash).xml
              artifactName: coverage-$(jobhash)
            condition: succeededOrFailed()
            displayName: 'Publish coverage artifact'
